debian/patches/git-updates.diff: update from upstream stable branch

diff --git a/debian/patches/git-updates.diff b/debian/patches/git-updates.diff
--- a/debian/patches/git-updates.diff
+++ b/debian/patches/git-updates.diff
@@ -1,10 +1,10 @@
 GIT update of https://sourceware.org/git/glibc.git/release/2.31/master from glibc-2.31
 
 diff --git a/NEWS b/NEWS
-index 292fbc595a..64e21b1c50 100644
+index 292fbc595a..472cba8cda 100644
 --- a/NEWS
 +++ b/NEWS
-@@ -4,6 +4,12 @@ See the end for copying conditions.
+@@ -4,6 +4,23 @@ See the end for copying conditions.
  
  Please send GNU C library bug reports via <https://sourceware.org/bugzilla/>
  using `glibc' in the "product" field.
@@ -12,11 +12,281 @@ index 292fbc595a..64e21b1c50 100644
 +Version 2.31.1
 +
 +The following bugs are resolved with this release:
++  [20543] Please move from .gnu.linkonce to comdat
++  [25487] sinl() stack corruption from crafted input (CVE-2020-10029)
 +  [25523] MIPS/Linux inline syscall template is miscompiled
++  [25623] test-sysvmsg, test-sysvsem, test-sysvshm fail with 2.31 on 32 bit and
++    old kernel
++  [25635] arm: Wrong sysdep order selection for soft-fp
++
++Security related changes:
++
++  CVE-2020-10029: Trigonometric functions on x86 targets suffered from stack
++  corruption when they were passed a pseudo-zero argument.  Reported by Guido
++  Vranken / ForAllSecure Mayhem.
 +
  
  Version 2.31
  
+diff --git a/configure b/configure
+index b959d2d988..3b98ec312f 100755
+--- a/configure
++++ b/configure
+@@ -4035,7 +4035,7 @@ if ${CC-cc} $CFLAGS $CPPFLAGS $LDFLAGS \
+ 	    -o conftest conftest.S 1>&5 2>&5; then
+   # Do a link to see if the backend supports IFUNC relocs.
+   $READELF -r conftest 1>&5
+-  LC_ALL=C $READELF -r conftest | grep 'no relocations' >/dev/null || {
++  LC_ALL=C $READELF -Wr conftest | grep -q 'IRELATIVE\|R_SPARC_JMP_IREL' && {
+     libc_cv_ld_gnu_indirect_function=yes
+   }
+ fi
+diff --git a/configure.ac b/configure.ac
+index 49b900c1ed..e20034f301 100644
+--- a/configure.ac
++++ b/configure.ac
+@@ -649,7 +649,7 @@ if ${CC-cc} $CFLAGS $CPPFLAGS $LDFLAGS \
+ 	    -o conftest conftest.S 1>&AS_MESSAGE_LOG_FD 2>&AS_MESSAGE_LOG_FD; then
+   # Do a link to see if the backend supports IFUNC relocs.
+   $READELF -r conftest 1>&AS_MESSAGE_LOG_FD
+-  LC_ALL=C $READELF -r conftest | grep 'no relocations' >/dev/null || {
++  LC_ALL=C $READELF -Wr conftest | grep -q 'IRELATIVE\|R_SPARC_JMP_IREL' && {
+     libc_cv_ld_gnu_indirect_function=yes
+   }
+ fi
+diff --git a/malloc/tst-mallocfork2.c b/malloc/tst-mallocfork2.c
+index 0602a94895..fc1fd64b21 100644
+--- a/malloc/tst-mallocfork2.c
++++ b/malloc/tst-mallocfork2.c
+@@ -62,6 +62,9 @@ static volatile sig_atomic_t sigusr1_received;
+    progress.  Checked by liveness_signal_handler.  */
+ static volatile sig_atomic_t progress_indicator = 1;
+ 
++/* Set to 1 if an error occurs in the signal handler.  */
++static volatile sig_atomic_t error_indicator = 0;
++
+ static void
+ sigusr1_handler (int signo)
+ {
+@@ -72,7 +75,8 @@ sigusr1_handler (int signo)
+   if (pid == -1)
+     {
+       write_message ("error: fork\n");
+-      abort ();
++      error_indicator = 1;
++      return;
+     }
+   if (pid == 0)
+     _exit (0);
+@@ -81,12 +85,14 @@ sigusr1_handler (int signo)
+   if (ret < 0)
+     {
+       write_message ("error: waitpid\n");
+-      abort ();
++      error_indicator = 1;
++      return;
+     }
+   if (status != 0)
+     {
+       write_message ("error: unexpected exit status from subprocess\n");
+-      abort ();
++      error_indicator = 1;
++      return;
+     }
+ }
+ 
+@@ -122,9 +128,25 @@ signal_sender (int signo, bool sleep)
+     }
+ }
+ 
++/* Children processes.  */
++static pid_t sigusr1_sender_pids[5] = { 0 };
++static pid_t sigusr2_sender_pid = 0;
++
++static void
++kill_children (void)
++{
++  for (size_t i = 0; i < array_length (sigusr1_sender_pids); ++i)
++    if (sigusr1_sender_pids[i] > 0)
++      kill (sigusr1_sender_pids[i], SIGKILL);
++  if (sigusr2_sender_pid > 0)
++    kill (sigusr2_sender_pid, SIGKILL);
++}
++
+ static int
+ do_test (void)
+ {
++  atexit (kill_children);
++
+   /* shared->barrier is intialized along with sigusr1_sender_pids
+      below.  */
+   shared = support_shared_allocate (sizeof (*shared));
+@@ -148,14 +170,13 @@ do_test (void)
+       return 1;
+     }
+ 
+-  pid_t sigusr2_sender_pid = xfork ();
++  sigusr2_sender_pid = xfork ();
+   if (sigusr2_sender_pid == 0)
+     signal_sender (SIGUSR2, true);
+ 
+   /* Send SIGUSR1 signals from several processes.  Hopefully, one
+      signal will hit one of the ciritical functions.  Use a barrier to
+      avoid sending signals while not running fork/free/malloc.  */
+-  pid_t sigusr1_sender_pids[5];
+   {
+     pthread_barrierattr_t attr;
+     xpthread_barrierattr_init (&attr);
+@@ -166,7 +187,7 @@ do_test (void)
+   }
+   for (size_t i = 0; i < array_length (sigusr1_sender_pids); ++i)
+     {
+-      sigusr1_sender_pids[i] = fork ();
++      sigusr1_sender_pids[i] = xfork ();
+       if (sigusr1_sender_pids[i] == 0)
+         signal_sender (SIGUSR1, false);
+     }
+@@ -211,7 +232,7 @@ do_test (void)
+         ++malloc_signals;
+       xpthread_barrier_wait (&shared->barrier);
+ 
+-      if (objects[slot] == NULL)
++      if (objects[slot] == NULL || error_indicator != 0)
+         {
+           printf ("error: malloc: %m\n");
+           for (size_t i = 0; i < array_length (sigusr1_sender_pids); ++i)
+@@ -225,10 +246,6 @@ do_test (void)
+   for (int slot = 0; slot < malloc_objects; ++slot)
+     free (objects[slot]);
+ 
+-  for (size_t i = 0; i < array_length (sigusr1_sender_pids); ++i)
+-    kill (sigusr1_sender_pids[i], SIGKILL);
+-  kill (sigusr2_sender_pid, SIGKILL);
+-
+   printf ("info: signals received during fork: %u\n", fork_signals);
+   printf ("info: signals received during free: %u\n", free_signals);
+   printf ("info: signals received during malloc: %u\n", malloc_signals);
+diff --git a/sysdeps/arm/be/nofpu/Implies b/sysdeps/arm/be/nofpu/Implies
+new file mode 100644
+index 0000000000..c90dd7fd5c
+--- /dev/null
++++ b/sysdeps/arm/be/nofpu/Implies
+@@ -0,0 +1 @@
++arm/nofpu
+diff --git a/sysdeps/arm/le/nofpu/Implies b/sysdeps/arm/le/nofpu/Implies
+new file mode 100644
+index 0000000000..c90dd7fd5c
+--- /dev/null
++++ b/sysdeps/arm/le/nofpu/Implies
+@@ -0,0 +1 @@
++arm/nofpu
+diff --git a/sysdeps/i386/sysdep.h b/sysdeps/i386/sysdep.h
+index b4bcd8fb6c..6094af8fec 100644
+--- a/sysdeps/i386/sysdep.h
++++ b/sysdeps/i386/sysdep.h
+@@ -61,7 +61,7 @@ lose: SYSCALL_PIC_SETUP							      \
+ 
+ # define SETUP_PIC_REG(reg) \
+   .ifndef GET_PC_THUNK(reg);						      \
+-  .section .gnu.linkonce.t.GET_PC_THUNK(reg),"ax",@progbits;		      \
++  .section .text.GET_PC_THUNK(reg),"axG",@progbits,GET_PC_THUNK(reg),comdat;  \
+   .globl GET_PC_THUNK(reg);						      \
+   .hidden GET_PC_THUNK(reg);						      \
+   .p2align 4;								      \
+@@ -97,7 +97,8 @@ GET_PC_THUNK(reg):							      \
+ 
+ # define SETUP_PIC_REG_STR(reg)						\
+   ".ifndef " GET_PC_THUNK_STR (reg) "\n"				\
+-  ".section .gnu.linkonce.t." GET_PC_THUNK_STR (reg) ",\"ax\",@progbits\n" \
++  ".section .text." GET_PC_THUNK_STR (reg) ",\"axG\",@progbits,"	\
++    GET_PC_THUNK_STR (reg) ",comdat\n"					\
+   ".globl " GET_PC_THUNK_STR (reg) "\n"					\
+   ".hidden " GET_PC_THUNK_STR (reg) "\n"				\
+   ".p2align 4\n"							\
+diff --git a/sysdeps/ieee754/ldbl-96/Makefile b/sysdeps/ieee754/ldbl-96/Makefile
+index 995e90d6da..6030adf7e7 100644
+--- a/sysdeps/ieee754/ldbl-96/Makefile
++++ b/sysdeps/ieee754/ldbl-96/Makefile
+@@ -17,5 +17,8 @@
+ # <https://www.gnu.org/licenses/>.
+ 
+ ifeq ($(subdir),math)
+-tests += test-canonical-ldbl-96 test-totalorderl-ldbl-96
++tests += test-canonical-ldbl-96 test-totalorderl-ldbl-96 test-sinl-pseudo
++ifeq ($(have-ssp),yes)
++CFLAGS-test-sinl-pseudo.c += -fstack-protector-all
+ endif
++endif # $(subdir) == math
+diff --git a/sysdeps/ieee754/ldbl-96/e_rem_pio2l.c b/sysdeps/ieee754/ldbl-96/e_rem_pio2l.c
+index 5f742321ae..bcdf20179f 100644
+--- a/sysdeps/ieee754/ldbl-96/e_rem_pio2l.c
++++ b/sysdeps/ieee754/ldbl-96/e_rem_pio2l.c
+@@ -210,6 +210,18 @@ __ieee754_rem_pio2l (long double x, long double *y)
+       return 0;
+     }
+ 
++  if ((i0 & 0x80000000) == 0)
++    {
++      /* Pseudo-zero and unnormal representations are not valid
++	 representations of long double.  We need to avoid stack
++	 corruption in __kernel_rem_pio2, which expects input in a
++	 particular normal form, but those representations do not need
++	 to be consistently handled like any particular floating-point
++	 value.  */
++      y[1] = y[0] = __builtin_nanl ("");
++      return 0;
++    }
++
+   /* Split the 64 bits of the mantissa into three 24-bit integers
+      stored in a double array.  */
+   exp = j0 - 23;
+diff --git a/sysdeps/ieee754/ldbl-96/test-sinl-pseudo.c b/sysdeps/ieee754/ldbl-96/test-sinl-pseudo.c
+new file mode 100644
+index 0000000000..f59b97769d
+--- /dev/null
++++ b/sysdeps/ieee754/ldbl-96/test-sinl-pseudo.c
+@@ -0,0 +1,41 @@
++/* Test sinl for pseudo-zeros and unnormals for ldbl-96 (bug 25487).
++   Copyright (C) 2020 Free Software Foundation, Inc.
++   This file is part of the GNU C Library.
++
++   The GNU C Library is free software; you can redistribute it and/or
++   modify it under the terms of the GNU Lesser General Public
++   License as published by the Free Software Foundation; either
++   version 2.1 of the License, or (at your option) any later version.
++
++   The GNU C Library is distributed in the hope that it will be useful,
++   but WITHOUT ANY WARRANTY; without even the implied warranty of
++   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
++   Lesser General Public License for more details.
++
++   You should have received a copy of the GNU Lesser General Public
++   License along with the GNU C Library; if not, see
++   <https://www.gnu.org/licenses/>.  */
++
++#include <math.h>
++#include <math_ldbl.h>
++#include <stdint.h>
++
++static int
++do_test (void)
++{
++  for (int i = 0; i < 64; i++)
++    {
++      uint64_t sig = i == 63 ? 0 : 1ULL << i;
++      long double ld;
++      SET_LDOUBLE_WORDS (ld, 0x4141,
++			 sig >> 32, sig & 0xffffffffULL);
++      /* The requirement is that no stack overflow occurs when the
++	 pseudo-zero or unnormal goes through range reduction.  */
++      volatile long double ldr;
++      ldr = sinl (ld);
++      (void) ldr;
++    }
++  return 0;
++}
++
++#include <support/test-driver.c>
 diff --git a/sysdeps/unix/sysv/linux/microblaze/sysdep.h b/sysdeps/unix/sysv/linux/microblaze/sysdep.h
 index ed873d9dd4..796663a23a 100644
 --- a/sysdeps/unix/sysv/linux/microblaze/sysdep.h
@@ -1098,6 +1368,44 @@ index cdfc0b1b58..a4cf1540fe 100644
      if (err)								\
        _ret = -_ret;							\
      _ret;								\
+diff --git a/sysdeps/unix/sysv/linux/msgctl.c b/sysdeps/unix/sysv/linux/msgctl.c
+index 27879e76cd..fd46aec1a0 100644
+--- a/sysdeps/unix/sysv/linux/msgctl.c
++++ b/sysdeps/unix/sysv/linux/msgctl.c
+@@ -21,6 +21,7 @@
+ #include <sysdep.h>
+ #include <shlib-compat.h>
+ #include <errno.h>
++#include <linux/posix_types.h>  /* For __kernel_mode_t.  */
+ 
+ #ifndef DEFAULT_VERSION
+ # ifndef __ASSUME_SYSVIPC_BROKEN_MODE_T
+@@ -61,7 +62,6 @@ __new_msgctl (int msqid, int cmd, struct msqid_ds *buf)
+ 
+   int ret = msgctl_syscall (msqid, cmd, buf);
+ 
+-#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+   if (ret >= 0)
+     {
+       switch (cmd)
+@@ -69,10 +69,16 @@ __new_msgctl (int msqid, int cmd, struct msqid_ds *buf)
+ 	case IPC_STAT:
+ 	case MSG_STAT:
+ 	case MSG_STAT_ANY:
++#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+ 	  buf->msg_perm.mode >>= 16;
++#else
++	  /* Old Linux kernel versions might not clear the mode padding.  */
++	  if (sizeof ((struct msqid_ds){0}.msg_perm.mode)
++	      != sizeof (__kernel_mode_t))
++	    buf->msg_perm.mode &= 0xFFFF;
++#endif
+ 	}
+     }
+-#endif
+ 
+   return ret;
+ }
 diff --git a/sysdeps/unix/sysv/linux/riscv/sysdep.h b/sysdeps/unix/sysv/linux/riscv/sysdep.h
 index 201bf9a91b..2bd9b16f32 100644
 --- a/sysdeps/unix/sysv/linux/riscv/sysdep.h
@@ -1256,3 +1564,242 @@ index 201bf9a91b..2bd9b16f32 100644
  	__asm__ volatile ( 						\
  	"scall\n\t" 							\
  	: "+r" (__a0)							\
+diff --git a/sysdeps/unix/sysv/linux/semctl.c b/sysdeps/unix/sysv/linux/semctl.c
+index 0c3eb0932f..30571af49f 100644
+--- a/sysdeps/unix/sysv/linux/semctl.c
++++ b/sysdeps/unix/sysv/linux/semctl.c
+@@ -22,6 +22,7 @@
+ #include <sysdep.h>
+ #include <shlib-compat.h>
+ #include <errno.h>
++#include <linux/posix_types.h>  /* For __kernel_mode_t.  */
+ 
+ /* Define a `union semun' suitable for Linux here.  */
+ union semun
+@@ -92,7 +93,6 @@ __new_semctl (int semid, int semnum, int cmd, ...)
+ 
+   int ret = semctl_syscall (semid, semnum, cmd, arg);
+ 
+-#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+   if (ret >= 0)
+     {
+       switch (cmd)
+@@ -100,10 +100,16 @@ __new_semctl (int semid, int semnum, int cmd, ...)
+         case IPC_STAT:
+         case SEM_STAT:
+         case SEM_STAT_ANY:
++#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+           arg.buf->sem_perm.mode >>= 16;
++#else
++	  /* Old Linux kernel versions might not clear the mode padding.  */
++	  if (sizeof ((struct semid_ds){0}.sem_perm.mode)
++	      != sizeof (__kernel_mode_t))
++	    arg.buf->sem_perm.mode &= 0xFFFF;
++#endif
+ 	}
+     }
+-#endif
+ 
+   return ret;
+ }
+diff --git a/sysdeps/unix/sysv/linux/shmctl.c b/sysdeps/unix/sysv/linux/shmctl.c
+index 39fa861e17..f41b359b8b 100644
+--- a/sysdeps/unix/sysv/linux/shmctl.c
++++ b/sysdeps/unix/sysv/linux/shmctl.c
+@@ -22,6 +22,7 @@
+ #include <sysdep.h>
+ #include <shlib-compat.h>
+ #include <errno.h>
++#include <linux/posix_types.h>  /* For __kernel_mode_t.  */
+ 
+ #ifndef DEFAULT_VERSION
+ # ifndef __ASSUME_SYSVIPC_BROKEN_MODE_T
+@@ -63,7 +64,6 @@ __new_shmctl (int shmid, int cmd, struct shmid_ds *buf)
+ 
+   int ret = shmctl_syscall (shmid, cmd, buf);
+ 
+-#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+   if (ret >= 0)
+     {
+       switch (cmd)
+@@ -71,10 +71,16 @@ __new_shmctl (int shmid, int cmd, struct shmid_ds *buf)
+         case IPC_STAT:
+         case SHM_STAT:
+         case SHM_STAT_ANY:
++#ifdef __ASSUME_SYSVIPC_BROKEN_MODE_T
+           buf->shm_perm.mode >>= 16;
++#else
++	  /* Old Linux kernel versions might not clear the mode padding.  */
++	  if (sizeof ((struct shmid_ds){0}.shm_perm.mode)
++	      != sizeof (__kernel_mode_t))
++	    buf->shm_perm.mode &= 0xFFFF;
++#endif
+ 	}
+     }
+-#endif
+ 
+   return ret;
+ }
+diff --git a/sysdeps/unix/sysv/linux/sparc/Makefile b/sysdeps/unix/sysv/linux/sparc/Makefile
+index b0d182a439..1475039677 100644
+--- a/sysdeps/unix/sysv/linux/sparc/Makefile
++++ b/sysdeps/unix/sysv/linux/sparc/Makefile
+@@ -11,8 +11,12 @@ ifeq ($(subdir),sysvipc)
+ sysdep_routines += getshmlba
+ endif
+ 
++ifeq ($(subdir),signal)
++sysdep_routines += sigreturn_stub
++endif
++
+ ifeq ($(subdir),nptl)
+ # pull in __syscall_error routine
+-libpthread-routines += sysdep
+-libpthread-shared-only-routines += sysdep
++libpthread-routines += sysdep sigreturn_stub
++libpthread-shared-only-routines += sysdep sigreturn_stub
+ endif
+diff --git a/sysdeps/unix/sysv/linux/sparc/sparc32/sigaction.c b/sysdeps/unix/sysv/linux/sparc/sparc32/sigaction.c
+index 6b2f664226..938aa7aa8c 100644
+--- a/sysdeps/unix/sysv/linux/sparc/sparc32/sigaction.c
++++ b/sysdeps/unix/sysv/linux/sparc/sparc32/sigaction.c
+@@ -24,8 +24,8 @@
+ #include <kernel_sigaction.h>
+ #include <sysdep.h>
+ 
+-static void __rt_sigreturn_stub (void);
+-static void __sigreturn_stub (void);
++void __rt_sigreturn_stub (void);
++void __sigreturn_stub (void);
+ 
+ #define STUB(act, sigsetsize) \
+   (act) ? ((unsigned long)((act->sa_flags & SA_SIGINFO)	\
+@@ -35,25 +35,3 @@ static void __sigreturn_stub (void);
+   (sigsetsize)
+ 
+ #include <sysdeps/unix/sysv/linux/sigaction.c>
+-
+-static
+-inhibit_stack_protector
+-void
+-__rt_sigreturn_stub (void)
+-{
+-  __asm__ ("mov %0, %%g1\n\t"
+-	   "ta	0x10\n\t"
+-	   : /* no outputs */
+-	   : "i" (__NR_rt_sigreturn));
+-}
+-
+-static
+-inhibit_stack_protector
+-void
+-__sigreturn_stub (void)
+-{
+-  __asm__ ("mov %0, %%g1\n\t"
+-	   "ta	0x10\n\t"
+-	   : /* no outputs */
+-	   : "i" (__NR_sigreturn));
+-}
+diff --git a/sysdeps/unix/sysv/linux/sparc/sparc32/sigreturn_stub.S b/sysdeps/unix/sysv/linux/sparc/sparc32/sigreturn_stub.S
+new file mode 100644
+index 0000000000..727cc94737
+--- /dev/null
++++ b/sysdeps/unix/sysv/linux/sparc/sparc32/sigreturn_stub.S
+@@ -0,0 +1,34 @@
++/* Sigreturn stub function used on sa_restore field.
++   Copyright (C) 2020 Free Software Foundation, Inc.
++   This file is part of the GNU C Library.
++
++   The GNU C Library is free software; you can redistribute it and/or
++   modify it under the terms of the GNU Lesser General Public
++   License as published by the Free Software Foundation; either
++   version 2.1 of the License, or (at your option) any later version.
++
++   The GNU C Library is distributed in the hope that it will be useful,
++   but WITHOUT ANY WARRANTY; without even the implied warranty of
++   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
++   Lesser General Public License for more details.
++
++   You should have received a copy of the GNU Lesser General Public
++   License along with the GNU C Library; if not, see
++   <https://www.gnu.org/licenses/>.  */
++
++#include <sysdep.h>
++
++/* These functions must not change the register window or the stack
++   pointer [1].
++
++   [1] https://lkml.org/lkml/2016/5/27/465  */
++
++ENTRY (__rt_sigreturn_stub)
++	mov	__NR_rt_sigreturn, %g1
++	ta	0x10
++END (__rt_sigreturn_stub)
++
++ENTRY (__sigreturn_stub)
++	mov	__NR_sigreturn, %g1
++	ta	0x10
++END (__sigreturn_stub)
+diff --git a/sysdeps/unix/sysv/linux/sparc/sparc64/sigaction.c b/sysdeps/unix/sysv/linux/sparc/sparc64/sigaction.c
+index 9c0dc2a630..4e26172321 100644
+--- a/sysdeps/unix/sysv/linux/sparc/sparc64/sigaction.c
++++ b/sysdeps/unix/sysv/linux/sparc/sparc64/sigaction.c
+@@ -22,21 +22,11 @@
+ #include <syscall.h>
+ #include <sysdep.h>
+ 
+-static void __rt_sigreturn_stub (void);
++/* Defined on sigreturn_stub.S.  */
++void __rt_sigreturn_stub (void);
+ 
+ #define STUB(act, sigsetsize) \
+   (((unsigned long) &__rt_sigreturn_stub) - 8),	\
+   (sigsetsize)
+ 
+ #include <sysdeps/unix/sysv/linux/sigaction.c>
+-
+-static
+-inhibit_stack_protector
+-void
+-__rt_sigreturn_stub (void)
+-{
+-  __asm__ ("mov %0, %%g1\n\t"
+-	   "ta	0x6d\n\t"
+-	   : /* no outputs */
+-	   : "i" (__NR_rt_sigreturn));
+-}
+diff --git a/sysdeps/unix/sysv/linux/sparc/sparc64/sigreturn_stub.S b/sysdeps/unix/sysv/linux/sparc/sparc64/sigreturn_stub.S
+new file mode 100644
+index 0000000000..add4766831
+--- /dev/null
++++ b/sysdeps/unix/sysv/linux/sparc/sparc64/sigreturn_stub.S
+@@ -0,0 +1,29 @@
++/* Sigreturn stub function used on sa_restore field.
++   Copyright (C) 2020 Free Software Foundation, Inc.
++   This file is part of the GNU C Library.
++
++   The GNU C Library is free software; you can redistribute it and/or
++   modify it under the terms of the GNU Lesser General Public
++   License as published by the Free Software Foundation; either
++   version 2.1 of the License, or (at your option) any later version.
++
++   The GNU C Library is distributed in the hope that it will be useful,
++   but WITHOUT ANY WARRANTY; without even the implied warranty of
++   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
++   Lesser General Public License for more details.
++
++   You should have received a copy of the GNU Lesser General Public
++   License along with the GNU C Library; if not, see
++   <https://www.gnu.org/licenses/>.  */
++
++#include <sysdep.h>
++
++/* This function must not change the register window or the stack
++   pointer [1].
++
++   [1] https://lkml.org/lkml/2016/5/27/465  */
++
++ENTRY (__rt_sigreturn_stub)
++	mov	__NR_rt_sigreturn, %g1
++	ta	0x6d
++END (__rt_sigreturn_stub)
