debian/debhelper.in/libc.postinst: Add support for upstart restarts and don't restart init when upgrading in chroots (Closes: #608903)
svn path=/glibc-package/branches/eglibc-2.17/; revision=5484

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -221,9 +221,25 @@ then
 	fi # end upgrading and $preversion lt 2.17
     fi # Upgrading
 
-    # Restart init. If it fails, there is nothing we can do, so 
-    # just ignore the error
-    telinit u 2> /dev/null || true ; sleep 1
+    # Restart init.  Currently handles chroots and upstart, and assumes
+    # anything else is going to not fail at behaving like sysvinit:
+    TELINIT=yes
+    if ischroot 2>/dev/null; then
+        # Don't bother trying to re-exec init from a chroot:
+        TELINIT=no
+    else
+        if [ -x "`which initctl`" ]; then
+            UPSTART=$(initctl version 2>/dev/null | awk '/upstart/ {gsub("\)",""); print $3}')
+            if dpkg --compare-versions "$UPSTART" lt-nl 1.6.1; then
+                # This is an old upstart that can't re-exec statefully:
+                TELINIT=no
+                touch /var/run/init.upgraded
+            fi
+        fi
+    fi
+    if [ "$TELINIT" = "yes" ]; then
+        telinit u 2>/dev/null || true ; sleep 1
+    fi
 fi
 
 #DEBHELPER#
