* Always try to restart init when needed, and ignore the possible errors.     Closes: #588922, 590175.
svn path=/glibc-package/trunk/; revision=4365

diff --git a/debian/debhelper.in/libc.postinst b/debian/debhelper.in/libc.postinst
--- a/debian/debhelper.in/libc.postinst
+++ b/debian/debhelper.in/libc.postinst
@@ -212,13 +212,9 @@ then
 	fi # end upgrading and $preversion lt 2.11-1
     fi # Upgrading
 
-    if [ "`uname -s`" = Linux ]; then
-      if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
-        # the devicenumber/inode pair of / is the same as that of /sbin/init's
-        # root, so we're *not* in a chroot
-        (telinit u ; sleep 1)
-      fi
-    fi
+    # Restart init. If it fails, there is nothing we can do, so 
+    # just ignore the error
+    telinit u 2> /dev/null || true ; sleep 1
 fi
 
 #DEBHELPER#
