[ Clint Adams ]   * debhelper.in/nscd.init: use lsb output functions.  Closes: #457661.
svn path=/glibc-package/trunk/; revision=2760

diff --git a/debian/debhelper.in/nscd.init b/debian/debhelper.in/nscd.init
--- a/debian/debhelper.in/nscd.init
+++ b/debian/debhelper.in/nscd.init
@@ -28,6 +28,7 @@ umask 022
 [ -f /etc/nscd.conf ] || exit 0
 [ -x "$DAEMON" ] || exit 0
 [ -d /var/run/nscd ] || mkdir -p /var/run/nscd
+. /lib/lsb/init-functions
 
 start_nscd()
 {
@@ -73,48 +74,48 @@ status()
 
 case "$1" in
 start)
-	echo -n "Starting $DESC: $NAME"
+	log_daemon_msg "Starting $DESC" "$NAME"
 	start_nscd
 	case "$?" in
-		0) echo "." ; exit 0 ;;
-		1) echo " (already running)." ; exit 0 ;;
-		*) echo " (failed)." ; exit 1 ;;
+		0) log_end_msg 0 ; exit 0 ;;
+		1) log_warning_msg " (already running)." ; exit 0 ;;
+		*) log_end_msg 1 ; exit 1 ;;
 	esac
 	;;
 stop)
-	echo -n "Stopping $DESC: $NAME"
+	log_daemon_msg "Stopping $DESC" "$NAME"
 	stop_nscd
 	case "$?" in
-		0) echo "." ; exit 0 ;;
-		1) echo " (not running)." ; exit 0 ;;
-		*) echo " (failed)." ; exit 1 ;;
+		0) log_end_msg 0 ; exit 0 ;;
+		1) log_warning_msg " (not running)." ; exit 0 ;;
+		*) log_end_msg 1 ; exit 1 ;;
 	esac
 	;;
 restart|force-reload|reload)
-	echo -n "Restarting $DESC: $NAME"
+	log_daemon_msg "Restarting $DESC" "$NAME"
 	stop_nscd
 	$DAEMON --invalidate passwd --invalidate group --invalidate hosts
 	case "$?" in
 	0|1)
 		start_nscd
 		case "$?" in
-			0) echo "." ; exit 0 ;;
-			1) echo " (failed -- old process is still running)." ; exit 1 ;;
-			*) echo " (failed to start)." ; exit 1 ;;
+			0) log_end_msg 0 ; exit 0 ;;
+			1) log_failure_msg " (failed -- old process is still running)." ; exit 1 ;;
+			*) log_failure_msg " (failed to start)." ; exit 1 ;;
 		esac
 		;;
 	*)
-		echo " (failed to stop)."
+		log_failure_msg " (failed to stop)."
 		exit 1
 		;;
 	esac
 	;;
 status)
-	echo -n "Status of $DESC service: "
+	log_daemon_msg "Status of $DESC service: "
 	status
 	case "$?" in
-		0) echo "not running." ; exit 1 ;;
-		1) echo "running." ; exit 0 ;;
+		0) log_failure_msg "not running." ; exit 1 ;;
+		1) log_success_msg "running." ; exit 0 ;;
 	esac
 	;;
 *)
